import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Google Pixel 7',
  description: 'Generated by create next app',
}

const header = (
  <header className='border-b border-gray-500 px-8 pb-2 flow-root font-sans'>
    <div className='float-left mt-5 mb-2 text-black text-xl font-bold tracking-wide'>Pixel 7</div>

    <div className='float-right mt-6'>
      <ul className='flex flex-row text-black text-xs items-center'>
        <li className='mx-2'>Overview</li>
        <li className='mx-2'>Tech Specs</li>
        <Link href="/" className="bg-blue-500 text-white mx-2 px-2 py-1 rounded-full focus:shadow-outline hover:bg-blue-600">Buy</Link>
      </ul>
    </div>
  </header>
)

const footer = (
  <footer className='px-36 py-6 text-center content-center text-slate-400 bg-gray-300'>
    <div className='border-t border-black pt-5'>
      <h3>Developed by Noah</h3>
      <div className='justify-center flex flex-row m-2'>
        <Link href="https://www.github.com/noahwhlim" className='mx-3'>
          <Image src="/github.svg" alt="github" width={25} height={25}/>
        </Link>
        <Link href="https://www.linkedin.com/in/noahwhlim">
          <Image src="/linkedin.svg" alt="linkedin" width={25} height={25}/>
        </Link>
      </div>
    </div>
  </footer>
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  )
}
